language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - nmadison@blackducksoftware.com

install: true
script:
  - mvn -U clean package
